// Vietnam cities/provinces map
export const VIETNAM_CITIES: { value: string; label: string }[] = [
  { value: 'An Giang', label: 'An Giang' },
  { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu' },
  { value: 'Bạc Liêu', label: 'Bạc Liêu' },
  { value: 'Bắc Kạn', label: 'Bắc Kạn' },
  { value: 'Bắc Giang', label: 'Bắc Giang' },
  { value: 'Bắc Ninh', label: 'Bắc Ninh' },
  { value: 'Bến Tre', label: 'Bến Tre' },
  { value: 'Bình Dương', label: 'Bình Dương' },
  { value: 'Bình Định', label: 'Bình Định' },
  { value: 'Bình Phước', label: 'Bình Phước' },
  { value: 'Bình Thuận', label: 'Bình Thuận' },
  { value: 'Cà Mau', label: 'Cà Mau' },
  { value: 'Cao Bằng', label: 'Cao Bằng' },
  { value: 'Cần Thơ', label: 'Cần Thơ' },
  { value: 'Đà Nẵng', label: 'Đà Nẵng' },
  { value: 'Đắk Lắk', label: 'Đắk Lắk' },
  { value: 'Đắk Nông', label: 'Đắk Nông' },
  { value: 'Điện Biên', label: 'Điện Biên' },
  { value: 'Đồng Nai', label: 'Đồng Nai' },
  { value: 'Đồng Tháp', label: 'Đồng Tháp' },
  { value: 'Gia Lai', label: 'Gia Lai' },
  { value: 'Hà Giang', label: 'Hà Giang' },
  { value: 'Hà Nam', label: 'Hà Nam' },
  { value: 'Hà Nội', label: 'Hà Nội' },
  { value: 'Hà Tĩnh', label: 'Hà Tĩnh' },
  { value: 'Hải Dương', label: 'Hải Dương' },
  { value: 'Hải Phòng', label: 'Hải Phòng' },
  { value: 'Hậu Giang', label: 'Hậu Giang' },
  { value: 'Hòa Bình', label: 'Hòa Bình' },
  { value: 'Thành phố Hồ Chí Minh', label: 'Thành phố Hồ Chí Minh' },
  { value: 'Hưng Yên', label: 'Hưng Yên' },
  { value: 'Khánh Hòa', label: 'Khánh Hòa' },
  { value: 'Kiên Giang', label: 'Kiên Giang' },
  { value: 'Kon Tum', label: 'Kon Tum' },
  { value: 'Lai Châu', label: 'Lai Châu' },
  { value: 'Lâm Đồng', label: 'Lâm Đồng' },
  { value: 'Lạng Sơn', label: 'Lạng Sơn' },
  { value: 'Lào Cai', label: 'Lào Cai' },
  { value: 'Long An', label: 'Long An' },
  { value: 'Nam Định', label: 'Nam Định' },
  { value: 'Nghệ An', label: 'Nghệ An' },
  { value: 'Ninh Bình', label: 'Ninh Bình' },
  { value: 'Ninh Thuận', label: 'Ninh Thuận' },
  { value: 'Phú Thọ', label: 'Phú Thọ' },
  { value: 'Phú Yên', label: 'Phú Yên' },
  { value: 'Quảng Bình', label: 'Quảng Bình' },
  { value: 'Quảng Nam', label: 'Quảng Nam' },
  { value: 'Quảng Ngãi', label: 'Quảng Ngãi' },
  { value: 'Quảng Ninh', label: 'Quảng Ninh' },
  { value: 'Quảng Trị', label: 'Quảng Trị' },
  { value: 'Sóc Trăng', label: 'Sóc Trăng' },
  { value: 'Sơn La', label: 'Sơn La' },
  { value: 'Tây Ninh', label: 'Tây Ninh' },
  { value: 'Thái Bình', label: 'Thái Bình' },
  { value: 'Thái Nguyên', label: 'Thái Nguyên' },
  { value: 'Thanh Hóa', label: 'Thanh Hóa' },
  { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
  { value: 'Tiền Giang', label: 'Tiền Giang' },
  { value: 'Trà Vinh', label: 'Trà Vinh' },
  { value: 'Tuyên Quang', label: 'Tuyên Quang' },
  { value: 'Vĩnh Long', label: 'Vĩnh Long' },
  { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
  { value: 'Yên Bái', label: 'Yên Bái' },
]

// Districts mapping for selected provinces/cities (used for finer filtering)
export const VIETNAM_DISTRICTS: Record<string, { value: string; label: string }[]> = {
  'Hà Nội': [
    { value: 'Ba Đình', label: 'Ba Đình' },
    { value: 'Hoàn Kiếm', label: 'Hoàn Kiếm' },
    { value: 'Đống Đa', label: 'Đống Đa' },
    { value: 'Cầu Giấy', label: 'Cầu Giấy' },
    { value: 'Thanh Xuân', label: 'Thanh Xuân' },
    { value: 'Hai Bà Trưng', label: 'Hai Bà Trưng' },
    { value: 'Hoàng Mai', label: 'Hoàng Mai' },
    { value: 'Long Biên', label: 'Long Biên' },
    { value: 'Tây Hồ', label: 'Tây Hồ' },
    { value: 'Hà Đông', label: 'Hà Đông' },
    { value: 'Ngã Tư Sở', label: 'Ngã Tư Sở' },
  ],
  'Thành phố Hồ Chí Minh': [
    { value: 'Quận 1', label: 'Quận 1' },
    { value: 'Quận 3', label: 'Quận 3' },
    { value: 'Quận 5', label: 'Quận 5' },
    { value: 'Quận 10', label: 'Quận 10' },
    { value: 'Quận Bình Thạnh', label: 'Quận Bình Thạnh' },
    { value: 'Quận Tân Bình', label: 'Quận Tân Bình' },
    { value: 'Quận Phú Nhuận', label: 'Quận Phú Nhuận' },
    { value: 'Quận 7', label: 'Quận 7' },
  ],
  'Đồng Nai': [
    { value: 'Biên Hòa', label: 'Biên Hòa' },
    { value: 'Long Thành', label: 'Long Thành' },
    { value: 'Nhơn Trạch', label: 'Nhơn Trạch' },
  ],
}
